### ISSUE TITLE
remoteConfig is returning null

### ISSUE THREAD

**Issue by akurnaz** [adaptyteam/AdaptySDK-Flutter#82]
remoteConfig method in AdaptyPaywall is returning null value in production. It is working correct in emulators. 

sdkVersion = '2.3.1'

My remote config: 
![Ekran Resmi 2023-03-02 17 04 06](https://user-images.githubusercontent.com/7497369/222450793-76872797-3935-4b65-a22e-65f14f932793.png)
![Ekran Resmi 2023-03-02 17 04 38](https://user-images.githubusercontent.com/7497369/222450886-7ef9e890-a40a-4ab1-8c50-d99049320e30.png)

**Comment by x401om** [comment]
Hi @akurnaz! Could you please clarify, what to you mean by "production" here? Also it would be great to provide a verbose log from the sdk.

**Comment by akurnaz** [comment]
@x401om By production I mean "after release". I only see the following message in Crashlytics that occurs where remoteConfig is called. I don't have verbose logs from the sdk.
`Null check operator used on a null value`

**Comment by ibrahimdevs** [comment]
@x401om I think, it is related with Flutter SDK. Everything is normal for my app which is on App Store. (It's adapty_flutter version is 2.2.4).
I upgrade the adapty_flutter to 2.4.1 and my paywall's remoteConfig data comes null now.

`var paywall = await Adapty().getPaywall(id: "my_paywall_id");
`

And paywall object's remoteConfig comes null, also I checked remoteConfigString is null too. I didn't change anything on my paywall's remote config data from Adapty Web Panel. Also it is still working on 2.2.4 without any problem.

There is something wrong in Adapty Flutter package, could you check it? It is very big issue, somebody can be affected on production too.

Thanks,

**Comment by x401om** [comment]
@ibrahimdevs did you fill the localized version of your remote config or you are still using the legacy one?
<img src="https://user-images.githubusercontent.com/1506401/227193745-0fa05350-e55b-4793-b76c-ae2e5ae55a38.png" width="600" />

Since 2.3.0 we have introduced [the paywalls localization](https://docs.adapty.io/docs/paywall#localizations) feature, that's why 2.2.4 works with legacy remote config, and 2.4.1 is not.

**Comment by ibrahimdevs** [comment]
@x401om Yes, I'm still using the legacy version. I think, if there is available legacy json, you should continue to provide the legacy json.
If an update is breaking change, it is better to put "Breaking Change" and inform us with email. 

Also it is better to edit docs.

![Screenshot 2023-03-23 at 15 07 11](https://user-images.githubusercontent.com/2773578/227199879-a2bbc6c0-f2be-4ee7-bc8f-336bafe1b186.png)

It is important because it effects directly how our paywalls are displayed. It would be a huge loss for me if I didn't notice and sent an update with current latest version.

**Comment by x401om** [comment]
@ibrahimdevs I apologize that our documentation was not clear enough. We have made some changes to ensure that such an issue will not happen again.

**Comment by x401om** [comment]
@akurnaz was you able to contact our support team?

**Comment by akurnaz** [comment]
@x401om I didn't but the problem was solved. You can close this issue.
