### ISSUE TITLE
Feature request: Fetching of all paywalls 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [adaptyteam/AdaptySDK-Flutter#88]
Hi, we have seen that new SDK has removed the method to fetch all paywalls which has caused a lot of changes inside our application. And I guess this is a major change and causing failure of some use cases we have developed on top of paywalls. There should be a way to get access to all paywalls. I see no use where you hardcode paywall IDs inside your app. A minimal API returning list of all paywall would make front-end more dynamic.

**Comment by x401om** [comment]
Hey @ch-muhammad-adil! 

We have deprecated the method that fetched all the paywalls because it is considered redundant and creates a high load on the system, which most developers don't require. Additionally, we have no plans to reintroduce this functionality in the future.

As an alternative, we recently introduced [placements](https://docs.adapty.io/docs/introducing-new-paywall-management-system-paywalls-20). We encourage you to refer to the documentation for more information. This approach will help you in hardcoding only the necessary placements, providing a more efficient solution.
