### ISSUE TITLE
Purchases on ios

### ISSUE THREAD

**Issue by Rest00rer** [adaptyteam/AdaptySDK-Flutter#89]
It takes too long for the native purchase window to open on ios: +- 20 sec.

**Comment by x401om** [comment]
Hey, @Rest00rer! AdaptySDK is not responsible for the timing of the native dialog presentation since we only initialize the payment and await the result in the payment queue.
I would recommend resetting the testing device and creating a new sandbox account to test again. I also suppose that this problem only occurs in the sandbox environment, an I right?

**Comment by n1kStas** [comment]
the same thing with us, a very long download. because of this, it is impossible to pass the review in the appstore
